# Generated by Django 2.2.28 on 2022-06-07 14:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_json_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonformmodel',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='response',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
